const Mock = require("mockjs");

export function test() {
  var data = Mock.mock({
    // 属性 list 的值是一个数组，其中含有 1 到 10 个元素
    "list|1-10": [
      {
        // 属性 id 是一个自增数，起始值为 1，每次增 1
        "id|+1": 1,
      },
    ],
  });
  return Mock.mock("@paragraph(1, 3)");
}

export function getLineTrains() {
  var data = Mock.mock({
    "array|20": [
      {
        "number|+2002": 11001002,
      },
    ],
  });

  return data;
}

export function signals() {
  return [
    {
      id: 3325,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "蓄电池温度（1=1℃，(0~255)线性对应(-55~200)）",
      signalCode: "1185_0_7",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-蓄电池温度（1=1℃，(0~255)线性对应(-55~200)）",
    },
    {
      id: 3324,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "充电机模块温度（1=1℃，(0~255)线性对应(-55~200)）",
      signalCode: "1184_0_7",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-充电机模块温度（1=1℃，(0~255)线性对应(-55~200)）",
    },
    {
      id: 3323,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "逆变器模块温度（1=1℃，(0~255)线性对应(-55~200)）",
      signalCode: "1183_0_7",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-逆变器模块温度（1=1℃，(0~255)线性对应(-55~200)）",
    },
    {
      id: 3322,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "HVM模块温度（1=1℃，(0~255)线性对应(-55~200)）",
      signalCode: "1182_0_7",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-HVM模块温度（1=1℃，(0~255)线性对应(-55~200)）",
    },
    {
      id: 3321,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "交流母线UW线电压（输出接触器KMA后端采样）",
      signalCode: "1180_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-交流母线UW线电压（输出接触器KMA后端采样）",
    },
    {
      id: 3320,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "逆变器输出UW线电压（输出接触器KMA前端采样）",
      signalCode: "1178_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-逆变器输出UW线电压（输出接触器KMA前端采样）",
    },
    {
      id: 3319,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "充电机蓄电池充电电流（充电机不工作时蓄电池放电电流）",
      signalCode: "1176_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-充电机蓄电池充电电流（充电机不工作时蓄电池放电电流）",
    },
    {
      id: 3318,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "充电机电路输出电流",
      signalCode: "1174_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-充电机电路输出电流",
    },
    {
      id: 3317,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "充电机电路输出电压（充电机不工作时蓄电池电压）",
      signalCode: "1172_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-充电机电路输出电压（充电机不工作时蓄电池电压）",
    },
    {
      id: 3316,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "逆变器接地检测电压",
      signalCode: "1170_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-逆变器接地检测电压",
    },
    {
      id: 3315,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "逆变器W相电流",
      signalCode: "1168_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-逆变器W相电流",
    },
    {
      id: 3314,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "逆变器V相电流",
      signalCode: "1166_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-逆变器V相电流",
    },
    {
      id: 3313,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "逆变器U相电流",
      signalCode: "1164_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-逆变器U相电流",
    },
    {
      id: 3312,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "交流母线UV线电压（输出接触器KMA后端采样）",
      signalCode: "1162_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-交流母线UV线电压（输出接触器KMA后端采样）",
    },
    {
      id: 3311,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "逆变器输出UV线电压（输出接触器KMA前端采样）",
      signalCode: "1160_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-逆变器输出UV线电压（输出接触器KMA前端采样）",
    },
    {
      id: 3310,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "LLC输出下半部电压",
      signalCode: "1158_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-LLC输出下半部电压",
    },
    {
      id: 3309,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "LLC输出上半部电压",
      signalCode: "1156_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-LLC输出上半部电压",
    },
    {
      id: 3308,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "斩波输出电压4",
      signalCode: "1154_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-斩波输出电压4",
    },
    {
      id: 3289,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "蓄电池温度（1=1℃，(0~255)线性对应(-55~200)）",
      signalCode: "1121_0_7",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-蓄电池温度（1=1℃，(0~255)线性对应(-55~200)）",
    },
    {
      id: 3288,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "充电机模块温度（1=1℃，(0~255)线性对应(-55~200)）",
      signalCode: "1120_0_7",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-充电机模块温度（1=1℃，(0~255)线性对应(-55~200)）",
    },
    {
      id: 3287,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "逆变器模块温度（1=1℃，(0~255)线性对应(-55~200)）",
      signalCode: "1119_0_7",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-逆变器模块温度（1=1℃，(0~255)线性对应(-55~200)）",
    },
    {
      id: 3286,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "HVM模块温度（1=1℃，(0~255)线性对应(-55~200)）",
      signalCode: "1118_0_7",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-HVM模块温度（1=1℃，(0~255)线性对应(-55~200)）",
    },
    {
      id: 3285,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "交流母线UW线电压（输出接触器KMA后端采样）",
      signalCode: "1116_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-交流母线UW线电压（输出接触器KMA后端采样）",
    },
    {
      id: 3284,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "逆变器输出UW线电压（输出接触器KMA前端采样）",
      signalCode: "1114_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-逆变器输出UW线电压（输出接触器KMA前端采样）",
    },
    {
      id: 3283,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "充电机蓄电池充电电流（充电机不工作时蓄电池放电电流）",
      signalCode: "1112_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-充电机蓄电池充电电流（充电机不工作时蓄电池放电电流）",
    },
    {
      id: 3282,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "充电机电路输出电流",
      signalCode: "1110_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-充电机电路输出电流",
    },
    {
      id: 3281,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "充电机电路输出电压（充电机不工作时蓄电池电压）",
      signalCode: "1108_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-充电机电路输出电压（充电机不工作时蓄电池电压）",
    },
    {
      id: 3280,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "逆变器接地检测电压",
      signalCode: "1106_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-逆变器接地检测电压",
    },
    {
      id: 3279,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "逆变器W相电流",
      signalCode: "1104_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-逆变器W相电流",
    },
    {
      id: 3278,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "逆变器V相电流",
      signalCode: "1102_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-逆变器V相电流",
    },
    {
      id: 3277,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "逆变器U相电流",
      signalCode: "1100_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-逆变器U相电流",
    },
    {
      id: 3276,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "交流母线UV线电压（输出接触器KMA后端采样）",
      signalCode: "1098_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-交流母线UV线电压（输出接触器KMA后端采样）",
    },
    {
      id: 3275,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "逆变器输出UV线电压（输出接触器KMA前端采样）",
      signalCode: "1096_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-逆变器输出UV线电压（输出接触器KMA前端采样）",
    },
    {
      id: 3274,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "LLC输出下半部电压",
      signalCode: "1094_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-LLC输出下半部电压",
    },
    {
      id: 3273,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "LLC输出上半部电压",
      signalCode: "1092_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-LLC输出上半部电压",
    },
    {
      id: 3272,
      lineName: "11",
      trainType: "E12",
      trainCoach: "1",
      submoduleName: "SIV系统",
      signalName: "斩波输出电压4",
      signalCode: "1090_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-1-斩波输出电压4",
    },
    {
      id: 3253,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "斩波输出电压3",
      signalCode: "1056_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-斩波输出电压3",
    },
    {
      id: 3252,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "斩波输出电压2",
      signalCode: "1054_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-斩波输出电压2",
    },
    {
      id: 3251,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "斩波输出电压1",
      signalCode: "1052_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-斩波输出电压1",
    },
    {
      id: 3250,
      lineName: "11",
      trainType: "E12",
      trainCoach: "8",
      submoduleName: "SIV系统",
      signalName: "线路输入电流（网流）",
      signalCode: "1050_0_15",
      unitName: null,
      signalType: null,
      signalStatus: null,
      key: "SIV系统-8-线路输入电流（网流）",
    },
  ];
}

export function alarmList(page, pagesize) {
  var data = {
    totalCount: 616,
    totalPages: 13,
    pageNo: 1,
    pageSize: 50,
    first: false,
    last: false,
    hasPrevious: true,
    hasNext: true,
    contentSize: 50,
    content: [
      {
        id: 21612,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "62017",
        evaluateDetecttime: 1726843958000,
        evaluateOcstime: 1726844274000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "C2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 705,
          lineName: "11",
          trainType: "E12",
          faultName: "C2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "62017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:C2:62017:f5ad9040-775f-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21611,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "72017",
        evaluateDetecttime: 1726843958000,
        evaluateOcstime: 1726844273000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "B2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 817,
          lineName: "11",
          trainType: "E12",
          faultName: "B2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "72017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:B2:72017:f5a81aac-775f-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21610,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "52017",
        evaluateDetecttime: 1726843958000,
        evaluateOcstime: 1726844274000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "D2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 593,
          lineName: "11",
          trainType: "E12",
          faultName: "D2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "52017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:D2:52017:f5a2a8ec-775f-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21609,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "22017",
        evaluateDetecttime: 1726841835000,
        evaluateOcstime: 1726841847000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "B1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 257,
          lineName: "11",
          trainType: "E12",
          faultName: "B1车DCU反馈 轮径超限报警",
          faultType: null,
          code: "22017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:B1:22017:03f9194e-775b-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21608,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "42017",
        evaluateDetecttime: 1726841835000,
        evaluateOcstime: 1726841847000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "D1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 481,
          lineName: "11",
          trainType: "E12",
          faultName: "D1车DCU反馈 轮径超限报警",
          faultType: null,
          code: "42017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:D1:42017:03f3ae82-775b-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21607,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "52017",
        evaluateDetecttime: 1726841835000,
        evaluateOcstime: 1726841847000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "D2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 593,
          lineName: "11",
          trainType: "E12",
          faultName: "D2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "52017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:D2:52017:03ee7516-775b-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21606,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "62017",
        evaluateDetecttime: 1726841835000,
        evaluateOcstime: 1726841847000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "C2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 705,
          lineName: "11",
          trainType: "E12",
          faultName: "C2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "62017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:C2:62017:03e923ae-775b-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21605,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "32017",
        evaluateDetecttime: 1726841835000,
        evaluateOcstime: 1726841847000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "C1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 369,
          lineName: "11",
          trainType: "E12",
          faultName: "C1车DCU反馈 轮径超限报警",
          faultType: null,
          code: "32017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:C1:32017:03e3d2e6-775b-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21604,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "72017",
        evaluateDetecttime: 1726841834000,
        evaluateOcstime: 1726841847000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "B2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 817,
          lineName: "11",
          trainType: "E12",
          faultName: "B2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "72017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:B2:72017:034d8462-775b-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21603,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "72017",
        evaluateDetecttime: 1726841496000,
        evaluateOcstime: 1726841826000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "B2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 817,
          lineName: "11",
          trainType: "E12",
          faultName: "B2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "72017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:B2:72017:39f66e9e-775a-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21602,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "42017",
        evaluateDetecttime: 1726841496000,
        evaluateOcstime: 1726841826000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "D1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 481,
          lineName: "11",
          trainType: "E12",
          faultName: "D1车DCU反馈 轮径超限报警",
          faultType: null,
          code: "42017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:D1:42017:39f0ff04-775a-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21601,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "52017",
        evaluateDetecttime: 1726841496000,
        evaluateOcstime: 1726841826000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "D2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 593,
          lineName: "11",
          trainType: "E12",
          faultName: "D2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "52017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:D2:52017:39eb7b6a-775a-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21600,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "62017",
        evaluateDetecttime: 1726841496000,
        evaluateOcstime: 1726841826000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "C2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 705,
          lineName: "11",
          trainType: "E12",
          faultName: "C2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "62017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:C2:62017:39e5fa5a-775a-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21599,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "32017",
        evaluateDetecttime: 1726841496000,
        evaluateOcstime: 1726841826000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "C1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 369,
          lineName: "11",
          trainType: "E12",
          faultName: "C1车DCU反馈 轮径超限报警",
          faultType: null,
          code: "32017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:C1:32017:39de4a6c-775a-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21598,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "72017",
        evaluateDetecttime: 1726841484000,
        evaluateOcstime: 1726841488000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "B2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 817,
          lineName: "11",
          trainType: "E12",
          faultName: "B2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "72017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:B2:72017:32c865dc-775a-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21597,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "62017",
        evaluateDetecttime: 1726841484000,
        evaluateOcstime: 1726841488000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "C2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 705,
          lineName: "11",
          trainType: "E12",
          faultName: "C2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "62017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:C2:62017:32bfb70c-775a-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21596,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "42017",
        evaluateDetecttime: 1726841484000,
        evaluateOcstime: 1726841488000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "D1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 481,
          lineName: "11",
          trainType: "E12",
          faultName: "D1车DCU反馈 轮径超限报警",
          faultType: null,
          code: "42017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:D1:42017:32b83176-775a-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21595,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "52017",
        evaluateDetecttime: 1726841484000,
        evaluateOcstime: 1726841488000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "D2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 593,
          lineName: "11",
          trainType: "E12",
          faultName: "D2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "52017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:D2:52017:32b2cc4a-775a-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21594,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "22017",
        evaluateDetecttime: 1726841483000,
        evaluateOcstime: 1726841488000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "B1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 257,
          lineName: "11",
          trainType: "E12",
          faultName: "B1车DCU反馈 轮径超限报警",
          faultType: null,
          code: "22017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:B1:22017:32291fae-775a-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21593,
        lineName: "11",
        trainType: "E12",
        trainNo: "11061062",
        evaluateCode: "32017",
        evaluateDetecttime: 1726841483000,
        evaluateOcstime: 1726841488000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "C1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 369,
          lineName: "11",
          trainType: "E12",
          faultName: "C1车DCU反馈 轮径超限报警",
          faultType: null,
          code: "32017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11061062:C1:32017:3221b386-775a-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21592,
        lineName: "11",
        trainType: "E12",
        trainNo: "11021022",
        evaluateCode: "13082",
        evaluateDetecttime: 1726795380000,
        evaluateOcstime: 1726795394000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 988,
          lineName: "11",
          trainType: "E12",
          faultName: "A1车SIV-B反馈 斩波输出不均压保护",
          faultType: null,
          code: "13082",
          level: "2",
          subsystem: "辅助逆变器箱",
          faultDesc:
            "四个斩波输出电压中任意一个电压与四路斩波电压的平均值差值到达80V以上",
          solution: "1. 检查网压 2. 检查HVM模块是否故障",
          reason:
            "四个斩波输出电压中任意一个电压与四路斩波电压的平均值差值到达80V以上",
          diagnoseLogic:
            "四个斩波输出电压中任意一个电压与四路斩波电压的平均值差值到达80V以上",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11021022:A1:13082:e6ca88c4-76ee-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21591,
        lineName: "11",
        trainType: "E12",
        trainNo: "11021022",
        evaluateCode: "13100",
        evaluateDetecttime: 1726795380000,
        evaluateOcstime: 1726795394000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 1006,
          lineName: "11",
          trainType: "E12",
          faultName: "A1车SIV-B反馈 SIV中等保护指示",
          faultType: null,
          code: "13100",
          level: "2",
          subsystem: "辅助逆变器箱",
          faultDesc: "有关联的中等故障发生",
          solution: "根据具体故障信息进行排查",
          reason: "有关联的中等故障发生",
          diagnoseLogic: "有关联的中等故障发生",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11021022:A1:13100:e6c4e752-76ee-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21590,
        lineName: "11",
        trainType: "E12",
        trainNo: "11019020",
        evaluateCode: "83023",
        evaluateDetecttime: 1726449276000,
        evaluateOcstime: 1726449281000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 1047,
          lineName: "11",
          trainType: "E12",
          faultName: "A2车SIV-A反馈 斩波输出不均压保护",
          faultType: null,
          code: "83023",
          level: "2",
          subsystem: "辅助逆变器箱",
          faultDesc:
            "四个斩波输出电压中任意一个电压与四路斩波电压的平均值差值到达80V以上",
          solution: "1. 检查网压 2. 检查HVM模块是否故障",
          reason:
            "四个斩波输出电压中任意一个电压与四路斩波电压的平均值差值到达80V以上",
          diagnoseLogic:
            "四个斩波输出电压中任意一个电压与四路斩波电压的平均值差值到达80V以上",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11019020:A2:83023:038e5cc0-73c9-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21589,
        lineName: "11",
        trainType: "E12",
        trainNo: "11019020",
        evaluateCode: "83041",
        evaluateDetecttime: 1726449276000,
        evaluateOcstime: 1726449281000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 1065,
          lineName: "11",
          trainType: "E12",
          faultName: "A2车SIV-A反馈 SIV中等保护指示",
          faultType: null,
          code: "83041",
          level: "2",
          subsystem: "辅助逆变器箱",
          faultDesc: "有关联的中等故障发生",
          solution: "根据具体故障信息进行排查",
          reason: "有关联的中等故障发生",
          diagnoseLogic: "有关联的中等故障发生",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11019020:A2:83041:03891184-73c9-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21588,
        lineName: "11",
        trainType: "E12",
        trainNo: "11001002",
        evaluateCode: "13059",
        evaluateDetecttime: 1726328129000,
        evaluateOcstime: 1726730764000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 965,
          lineName: "11",
          trainType: "E12",
          faultName: "A1车SIV-A反馈 蓄电池电压低红色报警指示",
          faultType: null,
          code: "13059",
          level: "3",
          subsystem: "蓄电池箱",
          faultDesc:
            "充电机温度传感器大于150℃或者小于-50℃（该故障为警告，充电机继续保持工作）",
          solution: "1.检查蓄电池；2.检查充电机是否工作",
          reason:
            "充电机温度传感器大于150℃或者小于-50℃（该故障为警告，充电机继续保持工作）",
          diagnoseLogic:
            "充电机温度传感器大于150℃或者小于-50℃（该故障为警告，充电机继续保持工作）",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11001002:A1:13059:f0693144-72ae-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21587,
        lineName: "11",
        trainType: "E12",
        trainNo: "11001002",
        evaluateCode: "13059",
        evaluateDetecttime: 1726324706000,
        evaluateOcstime: 1726324768000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 965,
          lineName: "11",
          trainType: "E12",
          faultName: "A1车SIV-A反馈 蓄电池电压低红色报警指示",
          faultType: null,
          code: "13059",
          level: "3",
          subsystem: "蓄电池箱",
          faultDesc:
            "充电机温度传感器大于150℃或者小于-50℃（该故障为警告，充电机继续保持工作）",
          solution: "1.检查蓄电池；2.检查充电机是否工作",
          reason:
            "充电机温度传感器大于150℃或者小于-50℃（该故障为警告，充电机继续保持工作）",
          diagnoseLogic:
            "充电机温度传感器大于150℃或者小于-50℃（该故障为警告，充电机继续保持工作）",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11001002:A1:13059:552a140c-72a7-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21586,
        lineName: "11",
        trainType: "E12",
        trainNo: "11031032",
        evaluateCode: "83076",
        evaluateDetecttime: 1726301401000,
        evaluateOcstime: 1726301718000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 1100,
          lineName: "11",
          trainType: "E12",
          faultName: "A2车SIV-B反馈 内部生命信号异常",
          faultType: null,
          code: "83076",
          level: "2",
          subsystem: "辅助逆变器箱",
          faultDesc: "控制单元内部通信异常",
          solution:
            "检查控制单元，对控制单元进行断电重启操作，若故障不能消除则更换控制单元",
          reason: "控制单元内部通信异常",
          diagnoseLogic: "控制单元内部通信异常",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11031032:A2:83076:b64b744c-7270-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21585,
        lineName: "11",
        trainType: "E12",
        trainNo: "11031032",
        evaluateCode: "83100",
        evaluateDetecttime: 1726301401000,
        evaluateOcstime: 1726301718000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 1124,
          lineName: "11",
          trainType: "E12",
          faultName: "A2车SIV-B反馈 SIV中等保护指示",
          faultType: null,
          code: "83100",
          level: "2",
          subsystem: "辅助逆变器箱",
          faultDesc: "有关联的中等故障发生",
          solution: "根据具体故障信息进行排查",
          reason: "有关联的中等故障发生",
          diagnoseLogic: "有关联的中等故障发生",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11031032:A2:83100:b63ed87c-7270-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21584,
        lineName: "11",
        trainType: "E12",
        trainNo: "11031032",
        evaluateCode: "83017",
        evaluateDetecttime: 1726301308000,
        evaluateOcstime: 1726301718000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 1041,
          lineName: "11",
          trainType: "E12",
          faultName: "A2车SIV-A反馈 内部生命信号异常",
          faultType: null,
          code: "83017",
          level: "2",
          subsystem: "辅助逆变器箱",
          faultDesc: "控制单元内部通信异常",
          solution:
            "检查控制单元，对控制单元进行断电重启操作，若故障不能消除则更换控制单元",
          reason: "控制单元内部通信异常",
          diagnoseLogic: "控制单元内部通信异常",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11031032:A2:83017:7e9874f0-7270-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21583,
        lineName: "11",
        trainType: "E12",
        trainNo: "11031032",
        evaluateCode: "83041",
        evaluateDetecttime: 1726301308000,
        evaluateOcstime: 1726301718000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 1065,
          lineName: "11",
          trainType: "E12",
          faultName: "A2车SIV-A反馈 SIV中等保护指示",
          faultType: null,
          code: "83041",
          level: "2",
          subsystem: "辅助逆变器箱",
          faultDesc: "有关联的中等故障发生",
          solution: "根据具体故障信息进行排查",
          reason: "有关联的中等故障发生",
          diagnoseLogic: "有关联的中等故障发生",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11031032:A2:83041:7e92dc16-7270-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21582,
        lineName: "11",
        trainType: "E12",
        trainNo: "11031032",
        evaluateCode: "13041",
        evaluateDetecttime: 1726301019000,
        evaluateOcstime: 1726301718000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 947,
          lineName: "11",
          trainType: "E12",
          faultName: "A1车SIV-A反馈 SIV中等保护指示",
          faultType: null,
          code: "13041",
          level: "2",
          subsystem: "辅助逆变器箱",
          faultDesc: "有关联的中等故障发生",
          solution: "根据具体故障信息进行排查",
          reason: "有关联的中等故障发生",
          diagnoseLogic: "有关联的中等故障发生",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11031032:A1:13041:d262e5c6-726f-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21581,
        lineName: "11",
        trainType: "E12",
        trainNo: "11031032",
        evaluateCode: "13017",
        evaluateDetecttime: 1726301019000,
        evaluateOcstime: 1726301718000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 923,
          lineName: "11",
          trainType: "E12",
          faultName: "A1车SIV-A反馈 内部生命信号异常",
          faultType: null,
          code: "13017",
          level: "2",
          subsystem: "辅助逆变器箱",
          faultDesc: "控制单元内部通信异常",
          solution:
            "检查控制单元，对控制单元进行断电重启操作，若故障不能消除则更换控制单元",
          reason: "控制单元内部通信异常",
          diagnoseLogic: "控制单元内部通信异常",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11031032:A1:13017:d25c0e7c-726f-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21580,
        lineName: "11",
        trainType: "E12",
        trainNo: "11031032",
        evaluateCode: "13076",
        evaluateDetecttime: 1726300906000,
        evaluateOcstime: 1726301718000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 982,
          lineName: "11",
          trainType: "E12",
          faultName: "A1车SIV-B反馈 内部生命信号异常",
          faultType: null,
          code: "13076",
          level: "2",
          subsystem: "辅助逆变器箱",
          faultDesc: "控制单元内部通信异常",
          solution:
            "检查控制单元，对控制单元进行断电重启操作，若故障不能消除则更换控制单元",
          reason: "控制单元内部通信异常",
          diagnoseLogic: "控制单元内部通信异常",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11031032:A1:13076:8fd31be0-726f-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21579,
        lineName: "11",
        trainType: "E12",
        trainNo: "11031032",
        evaluateCode: "13100",
        evaluateDetecttime: 1726300906000,
        evaluateOcstime: 1726301718000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 1006,
          lineName: "11",
          trainType: "E12",
          faultName: "A1车SIV-B反馈 SIV中等保护指示",
          faultType: null,
          code: "13100",
          level: "2",
          subsystem: "辅助逆变器箱",
          faultDesc: "有关联的中等故障发生",
          solution: "根据具体故障信息进行排查",
          reason: "有关联的中等故障发生",
          diagnoseLogic: "有关联的中等故障发生",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11031032:A1:13100:8fc5939e-726f-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21578,
        lineName: "11",
        trainType: "E12",
        trainNo: "11007008",
        evaluateCode: "83117",
        evaluateDetecttime: 1726296385000,
        evaluateOcstime: 1726296412000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 1141,
          lineName: "11",
          trainType: "E12",
          faultName: "A2车SIV-B反馈 蓄电池电压低黄色预警指示",
          faultType: null,
          code: "83117",
          level: "3",
          subsystem: "蓄电池箱",
          faultDesc: "充电机滞后臂下管故障反馈信号异常",
          solution: "1.检查蓄电池；2.检查充电机是否工作",
          reason: "充电机滞后臂下管故障反馈信号异常",
          diagnoseLogic: "充电机滞后臂下管故障反馈信号异常",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11007008:A2:83117:048fde2e-7265-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21577,
        lineName: "11",
        trainType: "E12",
        trainNo: "11007008",
        evaluateCode: "13058",
        evaluateDetecttime: 1726296073000,
        evaluateOcstime: 1726296413000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 964,
          lineName: "11",
          trainType: "E12",
          faultName: "A1车SIV-A反馈 蓄电池电压低黄色预警指示",
          faultType: null,
          code: "13058",
          level: "3",
          subsystem: "蓄电池箱",
          faultDesc: "充电机滞后臂下管故障反馈信号异常",
          solution: "1.检查蓄电池；2.检查充电机是否工作",
          reason: "充电机滞后臂下管故障反馈信号异常",
          diagnoseLogic: "充电机滞后臂下管故障反馈信号异常",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11007008:A1:13058:4a95e7c0-7264-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21576,
        lineName: "11",
        trainType: "E12",
        trainNo: "11023024",
        evaluateCode: "72017",
        evaluateDetecttime: 1726280961000,
        evaluateOcstime: 1726285435000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "B2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 817,
          lineName: "11",
          trainType: "E12",
          faultName: "B2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "72017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11023024:B2:72017:1f52ea9a-7241-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21575,
        lineName: "11",
        trainType: "E12",
        trainNo: "11023024",
        evaluateCode: "22017",
        evaluateDetecttime: 1726280961000,
        evaluateOcstime: 1726285435000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "B1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 257,
          lineName: "11",
          trainType: "E12",
          faultName: "B1车DCU反馈 轮径超限报警",
          faultType: null,
          code: "22017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11023024:B1:22017:1f4d8604-7241-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21574,
        lineName: "11",
        trainType: "E12",
        trainNo: "11023024",
        evaluateCode: "42017",
        evaluateDetecttime: 1726280961000,
        evaluateOcstime: 1726285435000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "D1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 481,
          lineName: "11",
          trainType: "E12",
          faultName: "D1车DCU反馈 轮径超限报警",
          faultType: null,
          code: "42017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11023024:D1:42017:1f483000-7241-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21573,
        lineName: "11",
        trainType: "E12",
        trainNo: "11023024",
        evaluateCode: "62017",
        evaluateDetecttime: 1726280961000,
        evaluateOcstime: 1726285435000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "C2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 705,
          lineName: "11",
          trainType: "E12",
          faultName: "C2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "62017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11023024:C2:62017:1f42e596-7241-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21572,
        lineName: "11",
        trainType: "E12",
        trainNo: "11023024",
        evaluateCode: "32017",
        evaluateDetecttime: 1726280961000,
        evaluateOcstime: 1726285435000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "C1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 369,
          lineName: "11",
          trainType: "E12",
          faultName: "C1车DCU反馈 轮径超限报警",
          faultType: null,
          code: "32017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11023024:C1:32017:1f3d8574-7241-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21571,
        lineName: "11",
        trainType: "E12",
        trainNo: "11023024",
        evaluateCode: "22017",
        evaluateDetecttime: 1726280928000,
        evaluateOcstime: 1726280953000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "B1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 257,
          lineName: "11",
          trainType: "E12",
          faultName: "B1车DCU反馈 轮径超限报警",
          faultType: null,
          code: "22017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11023024:B1:22017:0b948c52-7241-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21570,
        lineName: "11",
        trainType: "E12",
        trainNo: "11023024",
        evaluateCode: "32017",
        evaluateDetecttime: 1726280928000,
        evaluateOcstime: 1726280953000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "C1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 369,
          lineName: "11",
          trainType: "E12",
          faultName: "C1车DCU反馈 轮径超限报警",
          faultType: null,
          code: "32017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11023024:C1:32017:0b8e90a4-7241-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21569,
        lineName: "11",
        trainType: "E12",
        trainNo: "11023024",
        evaluateCode: "62017",
        evaluateDetecttime: 1726280927000,
        evaluateOcstime: 1726280952000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "C2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 705,
          lineName: "11",
          trainType: "E12",
          faultName: "C2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "62017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11023024:C2:62017:0af5c518-7241-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21568,
        lineName: "11",
        trainType: "E12",
        trainNo: "11023024",
        evaluateCode: "42017",
        evaluateDetecttime: 1726280927000,
        evaluateOcstime: 1726280952000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "D1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 481,
          lineName: "11",
          trainType: "E12",
          faultName: "D1车DCU反馈 轮径超限报警",
          faultType: null,
          code: "42017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11023024:D1:42017:0af0016e-7241-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21567,
        lineName: "11",
        trainType: "E12",
        trainNo: "11023024",
        evaluateCode: "52017",
        evaluateDetecttime: 1726280926000,
        evaluateOcstime: 1726280952000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "D2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 593,
          lineName: "11",
          trainType: "E12",
          faultName: "D2车DCU反馈 轮径超限报警",
          faultType: null,
          code: "52017",
          level: "3",
          subsystem: "VVVF箱",
          faultDesc: "检测到轮径值超出范围",
          solution: "检查轮径设置或检查轮对",
          reason: "检测到轮径值超出范围",
          diagnoseLogic: "检测到轮径值超出范围",
          faultImpact: null,
          type: "0",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11023024:D2:52017:0a561a0e-7241-11ef-9b81",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21566,
        lineName: "11",
        trainType: "E12",
        trainNo: "11007008",
        evaluateCode: "83086",
        evaluateDetecttime: 1726206557000,
        evaluateOcstime: 1726206563000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 1110,
          lineName: "11",
          trainType: "E12",
          faultName: "A2车SIV-B反馈 输入欠压保护",
          faultType: null,
          code: "83086",
          level: "3",
          subsystem: "辅助逆变器箱",
          faultDesc: "辅变输入电压低于950V",
          solution: "检查网压",
          reason: "辅变输入电压低于950V",
          diagnoseLogic: "辅变输入电压低于950V",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11007008:A2:83086:bc7442b6-7196-11ef-a565",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21565,
        lineName: "11",
        trainType: "E12",
        trainNo: "11007008",
        evaluateCode: "13099",
        evaluateDetecttime: 1726206557000,
        evaluateOcstime: 1726206563000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 1005,
          lineName: "11",
          trainType: "E12",
          faultName: "A1车SIV-B反馈 SIV轻微保护指示",
          faultType: null,
          code: "13099",
          level: "3",
          subsystem: "辅助逆变器箱",
          faultDesc: "有关联的轻微故障发生",
          solution: "根据具体故障信息进行排查",
          reason: "有关联的轻微故障发生",
          diagnoseLogic: "有关联的轻微故障发生",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11007008:A1:13099:bc6f24e8-7196-11ef-a565",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21564,
        lineName: "11",
        trainType: "E12",
        trainNo: "11007008",
        evaluateCode: "13027",
        evaluateDetecttime: 1726206557000,
        evaluateOcstime: 1726206563000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A1",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 933,
          lineName: "11",
          trainType: "E12",
          faultName: "A1车SIV-A反馈 输入欠压保护",
          faultType: null,
          code: "13027",
          level: "3",
          subsystem: "辅助逆变器箱",
          faultDesc: "辅变输入电压低于950V",
          solution: "检查网压",
          reason: "辅变输入电压低于950V",
          diagnoseLogic: "辅变输入电压低于950V",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11007008:A1:13027:bc69f05e-7196-11ef-a565",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
      {
        id: 21563,
        lineName: "11",
        trainType: "E12",
        trainNo: "11007008",
        evaluateCode: "83099",
        evaluateDetecttime: 1726206557000,
        evaluateOcstime: 1726206563000,
        evaluateCurrentstation: null,
        evaluateNextstation: null,
        evaluateLocation: null,
        unevaluateTraincoach: "A2",
        evaluateFlag: 1,
        evaluateOperator: null,
        evaluateEndtime: null,
        fileOrderNo: "100",
        info: {
          id: 1123,
          lineName: "11",
          trainType: "E12",
          faultName: "A2车SIV-B反馈 SIV轻微保护指示",
          faultType: null,
          code: "83099",
          level: "3",
          subsystem: "辅助逆变器箱",
          faultDesc: "有关联的轻微故障发生",
          solution: "根据具体故障信息进行排查",
          reason: "有关联的轻微故障发生",
          diagnoseLogic: "有关联的轻微故障发生",
          faultImpact: null,
          type: "1",
          alarmType: "0",
          repairPeriod: "1",
          faultShowCode: null,
        },
        uuid: "11007008:A2:83099:bc64d326-7196-11ef-a565",
        repairSuggest: null,
        location: null,
        station: null,
        expireDay: null,
      },
    ],
    pageable: {
      sort: {
        sorted: true,
        unsorted: false,
      },
      offset: 50,
      pageSize: 50,
      pageNumber: 1,
      paged: true,
      unpaged: false,
    },
    sort: {
      sorted: true,
      unsorted: false,
    },
    numberOfElements: 50,
  };
  const start = (page - 1) * pagesize;
  const end = start + pagesize;
  return {
    data: data.content.slice(start, end),
    total: 50,
  };
}
